[package]
name = "gazetteer"
version = "1.3.5"
edition = "2021"

[dependencies]
csv = "*"
glob = "0.3.0"
indicatif = "0.17.1"
itertools = "0.10.3"
flate2 = "1.0.24"
rayon = "1.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokenizers = "0.11.3"
toml = "0.5.9"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]

[features]
gui = []

[[bin]]
name = "gazetteer"