[package]
name = "gazetteer"
version = "0.4.1"
edition = "2021"

[dependencies]
counter = "0.5.5"
glob = "0.3.0"
indicatif = "0.17.0-rc.11"
itertools = "0.10.3"
linecount = "0.1.0"
ngrams = "1.0.1"
rayon = "1.5.3"
tokenizers = "0.11.3"
toml = "0.5.9"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]

[features]
server = []

[[bin]]
name = "gazetteer"
required-features = ["server"]