filter_path = "resources/filter_de.txt"
generate_abbrv = false
generate_ngrams = false

[corpora]
[corpora.example]
path = "resources/example.tsv"
generate_abbrv = true
generate_ngrams = true

[corpora.compresed]
path = "resources/example.tsv.gz"
generate_abbrv = true
generate_ngrams = true
