[default]
limits.bytes = "512MiB"
limits.data-form = "512MiB"
limits.file = "512MiB"
limits.form = "16MiB"
limits.json = "512MiB"
limits.msgpack = "512MiB"
limits.string = "512MiB"
template_dir = "templates/"
