filter_path = "resources/filter_de.txt"
generate_abbrv = false
generate_ngrams = false
max_deletes = 0

[corpora]
[corpora.taxa]
path = "resources/taxon/*.list"
generate_abbrv = true
max_deletes = 1

[corpora.vernacular]
path = "resources/vernacular/*.list"
max_deletes = 1
