filter_path = "resources/filter_de.txt"
generate_abbrv = false
generate_ngrams = false

[corpora]
[corpora.taxa]
path = "resources/taxon/*.list"
generate_abbrv = true
generate_ngrams = true

[corpora.vernacular]
path = "resources/vernacular/*.list"
