name: Rust

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    tags: 
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build binary with GUI
        run: cargo build --features=gui --release
          
      - name: Archive (w/GUI)
        run: cp target/release/gazetteer . && zip -r gazetteer-rs.${{ github.ref_name }}-gui.zip resources/ config.toml gazetteer Rocket.toml LICENSE && mv gazetteer gazetteer-gui
        
      - name: Build binary without GUI
        run: cargo build --release
        
      - name: Archive (w/o GUI)
        run: cp target/release/gazetteer . && zip -r gazetteer-rs.${{ github.ref_name }}-bin.zip resources/ config.toml gazetteer Rocket.toml LICENSE
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gazetteer-rs.${{ github.ref_name }}-bin.zip
            gazetteer-rs.${{ github.ref_name }}-gui.zip
            gazetteer
            gazetteer-gui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update latest tag
        uses: EndBug/latest-tag@v1.5.0
