name: Rust

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
    tags: 
      - v*
    

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: gazetteer-rs.${{ github.ref_name }}-bin.zip 
          files: |
            target/release/gazetteer
            resources/
            config.toml
            Rocket.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-gui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --features=gui --release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: gazetteer-rs.${{ github.ref_name }}-gui.zip 
          files: |
            target/release/gazetteer
            resources/
            static/
            templates/
            config.toml
            Rocket.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
